### ISSUE TITLE
Can't use it with Laravel Mix 4 and webpack 4

### ISSUE THREAD

**Issue by grafmouse** [lmeysel/laravel-mix-sass-resources-loader#2]
After upgrade to Laravel Mix 4 and webpack 4 package stops working. I've got this error:

> TypeError: Cannot read property 'loaders' of undefined
> at /laravel-mix-sass-resources-loader/dist/plugin.js:59:23

How can I make it work?

My implementation: 

```
require('laravel-mix-sass-resources-loader');
mix.sassResources('./node_modules/sass-mixins/mixins.scss');
```

**Comment by lmeysel** [comment]
laravel-mix uses vue-loader 15, which appears not to require a explicit sass-loader configuration. For laravel-mix 2 it was required to modify the vue-loader which then ran into that error.

I pushed a fix for it, but was not able to do a larger test on it (due to too much work) - just give it a try...
